name: Get Active Self-Hosted Runners

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  get-active-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get active self-hosted runners
        id: get-active-runners
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_PAT }}
        run: |
          gh api -H "Accept: application/vnd.github+json" \
                 -H "X-GitHub-Api-Version: 2022-11-28" \
                 /repos/crajapakshe/github-self-hosted-runners/actions/runners > runners.json
          cat runners.json

      - name: Display active runners
        run: |
          echo "Active self-hosted runners:"
          cat runners.json

      - name: Add online runners to GitHub step summary
        run: |
          echo "## Online Self-Hosted Runners" >> $GITHUB_STEP_SUMMARY
          jq -r '.runners[] | select(.status == "online") | "- \(.name) (\(.os))"' runners.json >> $GITHUB_STEP_SUMMARY



