name: Get Active Self-Hosted Runners

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  get-active-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get active self-hosted runners
        id: get-active-runners
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEVOPS_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const runners = await github.rest.actions.listSelfHostedRunnersForRepo({
              owner,
              repo
            });
            const activeRunners = runners.data.runners.filter(runner => runner.status === 'online');
            core.setOutput("active-runners", JSON.stringify(activeRunners));

      - name: Display active runners
        run: |
          echo "Active self-hosted runners:"
          echo "${{ steps.get-active-runners.outputs['active-runners'] }}"

