name: Get Self-Hosted Runners

on:
  workflow_dispatch:

jobs:
  get-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4                   

      - name: Get self-hosted runners
        id: get-runners
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DEVOPS_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const runners = await github.rest.actions.listSelfHostedRunnersForRepo({
              owner,
              repo
            });
            core.setOutput("runners", JSON.stringify(runners.data));

      - name: Display runners
        run: |
          echo "Self-hosted runners:"
          echo "${{ steps.get-runners.outputs.runners }}"

